DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/Data/ApplicationDbContext.cs, DevForge Connect/Entities/Identity/ApplicationUser.cs, DevForge Connect/Entities/ProjectSubmission.cs, DevForge Connect/Migrations/20240910002723_CreatingProjectSubmissionEntity.Designer.cs, DevForge Connect/Migrations/20240910002723_CreatingProjectSubmissionEntity.cs, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/Views/ProjectSubmissions/Delete.cshtml, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/Views/ProjectSubmissions/Edit.cshtml, DevForge Connect/Views/ProjectSubmissions/Index.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml
I went ahead and created an entity class for Project Submission. Automatically generated the HTML Views. We can adjust as needed for any new columns or designs we want.
public int Id { get; set; }
public string Title { get; set; } = string.Empty;
public string Description { get; set; } = string.Empty;
public DateTime Deadline { get; set; }
public string Funding { get; set; } = string.Empty;
[Required] public string? creatorId { get; set; }
public ApplicationUser? Creator { get; set; }
=> Create the basic entity classes for Project Submission.

README.md
=> Added a basic readme file

DevForge Connect/Controllers/ProjectBidsController.cs, DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/Controllers/StatusController.cs, DevForge Connect/Data/ApplicationDbContext.cs, DevForge Connect/DevForge Connect.csproj, DevForge Connect/Entities/ProjectBid.cs, DevForge Connect/Entities/ProjectSubmission.cs, DevForge Connect/Entities/Status.cs, DevForge Connect/Migrations/20240917035526_ProjectBid.Designer.cs, DevForge Connect/Migrations/20240917035526_ProjectBid.cs, DevForge Connect/Migrations/20240917151634_statusTable.Designer.cs, DevForge Connect/Migrations/20240917151634_statusTable.cs, DevForge Connect/Migrations/20240917151900_statusTable2.Designer.cs, DevForge Connect/Migrations/20240917151900_statusTable2.cs, DevForge Connect/Migrations/20240917152014_statusTable3.Designer.cs, DevForge Connect/Migrations/20240917152014_statusTable3.cs, DevForge Connect/Views/ProjectBids/Create.cshtml, DevForge Connect/Views/ProjectBids/Delete.cshtml, DevForge Connect/Views/ProjectBids/Details.cshtml, DevForge Connect/Views/ProjectBids/Edit.cshtml, DevForge Connect/Views/ProjectBids/Index.cshtml, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml, DevForge Connect/Views/Status/Create.cshtml, DevForge Connect/Views/Status/Delete.cshtml, DevForge Connect/Views/Status/Details.cshtml, DevForge Connect/Views/Status/Edit.cshtml, DevForge Connect/Views/Status/Index.cshtml
Changes
- Created DB Entity ProjectBid
- Generated the basic view / HTML for Project Bid entity. 
- Added bids table to Project Submission details view
- Created DB Entity for Statuses for both Bids / Project Submissions
=> Created the DB entity for bidding. Generated the basic views to match

DevForge Connect/Views/ProjectSubmissions/Create.cshtml
Changes
- Actually fixed the merge conflict that happened in class Friday. I rushed a bit and didn't fully repair.
=> Fixed Merge Conflict

DevForge Connect/Controllers/TeamInvitesController.cs, DevForge Connect/Controllers/TeamsController.cs, DevForge Connect/Entities/Identity/ApplicationUser.cs, DevForge Connect/Entities/TeamInvite.cs, DevForge Connect/Migrations/20240925023744_team-invite.Designer.cs, DevForge Connect/Migrations/20240925023744_team-invite.cs, DevForge Connect/Migrations/20240925023835_user.Designer.cs, DevForge Connect/Migrations/20240925023835_user.cs, DevForge Connect/Models/TeamDetailsVm.cs, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/Views/ProjectSubmissions/Index.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml, DevForge Connect/Views/Teams/Details.cshtml, DevForge Connect/Views/Teams/_TeamInvitePartial.cshtml, DevForge Connect/wwwroot/js/Table_Initializers/BidTable.js, DevForge Connect/wwwroot/js/Table_Initializers/ProjectSubmissionTable.js
Changes
- Added DataTables JS Library to project
- Refined the team invite models and made it possible to send a team invite
=> Further Improved The Team Invite Process | Added Data tables JS Library to Project

DevForge Connect/Areas/Identity/Pages/Account/Register.cshtml, DevForge Connect/Areas/Identity/Pages/Account/Register.cshtml.cs, DevForge Connect/Controllers/AdministrationController.cs, DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/Startup.cs, DevForge Connect/Views/Administration/CreateRole.cshtml, DevForge Connect/Views/Administration/View_Models/CreateRoleViewModel.cs, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml
Changes
- Cleaned up some of the views from containing dropdowns for userId
- Added Identity Roles
- Added view to Create New Roles (admin only)
- Modified the registration to set user role to client or developer based upon toggle switch
Note - You will need to create these records in AspNetRoles table and probably assign the admin role to your user in AspNetUserRoles table for all functionality to work
=> Identity Role Setup

DevForge Connect/Views/ProjectSubmissions/Index.cshtml, DevForge Connect/wwwroot/js/LLM_API/api.js
Changes
- Modified the chatbots html response to respect white space a bit better
- Integrated NLP tags for Project Submission Index Page
=> Cleaned Up Chatbot White Space Handling & Integrated NLP Tags For Index

DevForge Connect/Areas/Identity/Pages/Account/Register.cshtml.cs, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml
Changes
- Modified the navbar to respect developer / client / admin role permissions.
- Modified the register method so that admin role is auto created if it doesn't already exist. 
- Added create button to the project submission details page. 
Note - please double check that the changes look correct before merging them in before the DEMO today. I was having a hard time installing SQL Server express for my laptop machine for some reason and programmed this without DB access.
=> Modified the navbar to respect role permissions.

DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/Views/ProjectSubmissions/Edit.cshtml
Changes
- Added NLP tags to project submission details page. 
- Fixed the ability to edit project submissions
- Made the Project Submission Details TextArea larger by defaultt
=> NLP Further Integration

DevForge Connect/Views/ProjectSubmissions/Index.cshtml
Changes
- Improved the look of the Project Submission Index Table (Removed Creator Column and placed in descriptor portion)
- Added the button permission handling so that only the creator / admins can delete or edit projects
- Some style changes
=> Modified the Project Submission Index Page

DevForge Connect/Views/ProjectSubmissions/Index.cshtml, DevForge Connect/wwwroot/js/Table_Initializers/ProjectSubmissionTable.js
- Added another data table to only include a particular users project followed by all other projects in another data table.
- Tweaked descriptions over 1000 characters to have "..." after them to make it more understandable.
- Added the ability to see who created the project as before you could only see creator if description was over 1000 characters.
- tweaked UI
- Minor fixes and refactoring of code that handles descriptions.
=> Dynamic Project Submission Index

DevForge Connect/Controllers/TeamInvitesController.cs, DevForge Connect/Views/Shared/_Layout.cshtml
Changes
- Added a notification button / indicator on the navbar
- Created functionality to accept / decline team invites.
=> Created the notification modal for accepting team invites.

DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/Entities/ProjectBid.cs, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/Views/ProjectSubmissions/Index.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml, DevForge Connect/wwwroot/lib/bootstrap/dist/css/bootstrap.css
- Fixed Project bids buttons
- Added ability to access details of project submission.
- Fixed some minor bugs with the navbar UI.
- Updated submit button to only appear for admins and developers
- Updated notification to include bids.
=> Bid Notifications and Fixes

DevForge Connect/Controllers/UserProfilesController.cs, DevForge Connect/Entities/UserProfiles.cs, DevForge Connect/Migrations/20241027190140_userExpirience.Designer.cs, DevForge Connect/Migrations/20241027190140_userExpirience.cs, DevForge Connect/Views/Shared/_LoginPartial.cshtml, DevForge Connect/Views/UserProfiles/Create.cshtml, DevForge Connect/Views/UserProfiles/Delete.cshtml, DevForge Connect/Views/UserProfiles/Edit.cshtml, DevForge Connect/Views/UserProfiles/Index.cshtml
I pulled from the current master and re-added all of my changes to the user profiles (Auto-create profile, fixed pfp not loading in navbar, and added user expirience).
=> Fixed User Profiles and Added Expirience

AI_LLM_Analysis/textGen.py, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/wwwroot/css/site.css, DevForge Connect/wwwroot/js/LLM_API/api.js, DevForge Connect/wwwroot/js/chat.js
Changes
- Created an experimental UI for the chatbot.
- Tweaked the prompting we are sending to Gemini in the hope it gives us a better conversion and requirement gathering. 
Future Changes
- In the future I would like to make it that when chatbot responds we automatically parse the details into form submission fields.
=> Created a experimental UI for chatbot. Tweaked Chatbot Prompting

DevForge Connect/Controllers/UserProfilesController.cs, DevForge Connect/Entities/UserProfiles.cs, DevForge Connect/Migrations/20241102200052_userProfileNLPTags.Designer.cs, DevForge Connect/Migrations/20241102200052_userProfileNLPTags.cs, DevForge Connect/Views/UserProfiles/Index.cshtml
Changes
- Modified the User Profile entity to store NLP Tags
- Modified the User Profile index page to show the first 3 NLP tags
=> Added NLP Support to UserProfiles.

DevForge Connect/Controllers/ProjectBidsController.cs, DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/Controllers/UserTeamsController.cs, DevForge Connect/Entities/ProjectBid.cs, DevForge Connect/Entities/ProjectSubmission.cs, DevForge Connect/Migrations/20241110163513_TeamIntegration.Designer.cs, DevForge Connect/Migrations/20241110163513_TeamIntegration.cs, DevForge Connect/Services/TeamBuilder/ITeamBuilder.cs, DevForge Connect/Services/TeamBuilder/TeamBuilder.cs, DevForge Connect/Startup.cs, DevForge Connect/Views/ProjectBids/Create.cshtml, DevForge Connect/Views/ProjectBids/Index.cshtml, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/Views/Teams/Create.cshtml, DevForge Connect/Views/Teams/Details.cshtml, DevForge Connect/Views/UserTeams/Delete.cshtml
Changes
- Made it possible to leave or remove team members (only the team leader or admins can remove other users)
- Cleaned up some of the UI for removing users.
=> Improve Team Management

DevForge Connect/Controllers/ProjectBidsController.cs, DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/DevForge Connect.csproj, DevForge Connect/Migrations/20241014183152_reconfigure.cs, DevForge Connect/Views/ProjectBids/Create.cshtml, DevForge Connect/Views/ProjectSubmissions/Details.cshtml, DevForge Connect/wwwroot/js/LLM_API/api.js
- Bids can only be seen by creator.
- Bids can not be placed by creator.
- Bids status changes when project creator views details of bid.
- Bid notifaction now clear when viewing bids.
- Bids can now be accepted.
- Bids can now be declined.
- Once a bid is accepted other bids are removed from the project.
- Once a bid is accepted other bids can not be placed.
- automatically applies statuses to status table.
- Cleaned up bid and automated some data entry.
- After submitting bid, it redirects back to project page.
=> BidsUpdate

AI_LLM_Analysis/textGen.py, DevForge Connect/Controllers/ProjectSubmissionsController.cs, DevForge Connect/DevForge Connect.csproj, DevForge Connect/Views/ProjectSubmissions/Create.cshtml, DevForge Connect/Views/ProjectSubmissions/ModifyProjectDeadline.cshtml, DevForge Connect/Views/ProjectSubmissions/ModifyProjectDescription.cshtml, DevForge Connect/Views/ProjectSubmissions/ModifyProjectFunding.cshtml, DevForge Connect/Views/ProjectSubmissions/ModifyProjectTeam.cshtml, DevForge Connect/Views/ProjectSubmissions/ModifyProjectTitle.cshtml, DevForge Connect/Views/Shared/_Layout.cshtml, DevForge Connect/wwwroot/js/LLM_API/api.js, DevForge Connect/wwwroot/js/chat.js
Changes
- Added Views for the various questions
- Added controller endpoints for the questions
- Improvement to chat prompts for JSON parsing
=> Basic Interview Style Flow

DevForge_Connect/Controllers/AdministrationController.cs, DevForge_Connect/Views/Administration/Dashboard.cshtml, DevForge_Connect/Views/ProjectSubmissions/Create.cshtml, DevForge_Connect/Views/ProjectSubmissions/ModifyProjectDescription.cshtml, DevForge_Connect/Views/Shared/_Layout.cshtml, DevForge_Connect/wwwroot/js/chat.js
- Conflict fix for "Cleaned Up AI JSON Parsing Process" PR number 55 by Johnny
=> Conflict Fix

AI_LLM_Analysis/textGen.py
Change
- Modified the Gemini Prompt to hopefully give concise, but still helpful responses
- Should JSON parse correctly
=> Improved Prompts
